### PR TITLE
Fix composer.json

### PR DESCRIPTION
**Pull request by wtfred**
Remove extra coma

### CODE REVIEW

**Comment by wtfred** [comment]
Btw thanks a lot to the sponsor, i was starting to turn back to sys_actions while i was preparing all my migration to TYPO3 v7 !

**Comment by wtfred** [comment]
Hello,
I don't want to rush you guys, but it would be really nice if you could release a new version on the TER with this PR. At the moment we can't install tc_beuser 3.0.0 via TYPO3 backend, because of the composer error :s
Thanks :)

**Comment by kartolo** [comment]
just released 3.0.1.

**Comment by wtfred** [comment]
Nice, thanks :)

**Pull request merged**
